-- 코드를 입력하세요
SELECT 
    WAREHOUSE_ID
    , WAREHOUSE_NAME
    , ADDRESS
    , IF(FREEZER_YN IS NULL, 'N', FREEZER_YN)
FROM FOOD_WAREHOUSE
WHERE 1=1
    AND LOCATE('경기도', ADDRESS) > 0
ORDER BY WAREHOUSE_ID ASC