SELECT b.BOOK_ID, a.AUTHOR_NAME, DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d')
FROM BOOK as b JOIN AUTHOR as a ON b.AUTHOR_ID = a.AUTHOR_ID 
WHERE 1=1
    AND b.CATEGORY = '경제'
ORDER BY b.PUBLISHED_DATE ASC;
